## Handling Imbalanced Dataset

In [56]:
import pandas as pd
df=pd.read_csv('creditcard.csv')
import numpy as np

In [57]:
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [58]:
df.shape

(284807, 31)

In [59]:
df['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [60]:
# Dependendent and Indipendent
X=df.drop(columns=['Class'])
y=df['Class']

In [61]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [62]:
log_class=LogisticRegression()
grid={'C':10.0**np.arange(-2,3),'penalty':['l1','l2']}
cv=KFold(n_splits=5,shuffle=False,random_state=None)

In [63]:
clf=GridSearchCV(log_class,grid,cv=cv,n_jobs=-1,scoring='f1_macro')

In [64]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7)

In [65]:
clf.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
25 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 447, in _check_solver
    raise ValueError(
Valu

GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [66]:
y_pred=clf.predict(X_test)

In [67]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85314
           1       0.66      0.70      0.68       129

    accuracy                           1.00     85443
   macro avg       0.83      0.85      0.84     85443
weighted avg       1.00      1.00      1.00     85443



In [68]:
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[85268    46]
 [   39    90]]
0.9990051847430451


In [69]:
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier()
clf.fit(X_train,y_train)

RandomForestClassifier()

In [70]:
y_pred=clf.predict(X_test)

In [71]:
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85314
           1       0.98      0.84      0.90       129

    accuracy                           1.00     85443
   macro avg       0.99      0.92      0.95     85443
weighted avg       1.00      1.00      1.00     85443

[[85312     2]
 [   21   108]]
0.9997308146951769


In [72]:
y_train.value_counts()

0    199001
1       363
Name: Class, dtype: int64

In [18]:
## As the 1 is comparitively less we increase the weight of each 1 , which means we give more importants to 1 

In [19]:
class_weight=dict({0:1,1:100})


In [20]:
clf=RandomForestClassifier(class_weight=class_weight)
clf.fit(X_train,y_train)

RandomForestClassifier(class_weight={0: 1, 1: 100})

In [21]:
y_pred=clf.predict(X_test)

In [22]:
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    227453
           1       0.94      0.68      0.79       393

    accuracy                           1.00    227846
   macro avg       0.97      0.84      0.90    227846
weighted avg       1.00      1.00      1.00    227846

[[227437     16]
 [   125    268]]
0.9993811609595955


## Under Sampling

In [83]:
## Reduce the points of maximum labels

In [84]:
y_train.value_counts()

0    199001
1       363
Name: Class, dtype: int64

In [85]:
from collections import Counter
from imblearn.under_sampling import NearMiss
ns=NearMiss(sampling_strategy=0.8)
X_train_ns,y_train_ns=ns.fit_resample(X_train,y_train)
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_train_ns)))

The number of classes before fit Counter({0: 199001, 1: 363})
The number of classes after fit Counter({0: 453, 1: 363})


In [86]:
X_test_ns,y_test_ns=ns.fit_resample(X_test,y_test
                                   )

## 0.8*X=360 X=360/0.8=450

In [87]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(X_train_ns,y_train_ns)

RandomForestClassifier()

In [88]:
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[69521 15793]
 [    5   124]]
0.8151048067132475
              precision    recall  f1-score   support

           0       1.00      0.81      0.90     85314
           1       0.01      0.96      0.02       129

    accuracy                           0.82     85443
   macro avg       0.50      0.89      0.46     85443
weighted avg       1.00      0.82      0.90     85443



## Over Sampling

In [89]:
from imblearn.over_sampling import RandomOverSampler
os=RandomOverSampler(sampling_strategy=0.5)

In [90]:
X_train_ns,y_train_ns=os.fit_resample(X_train,y_train)
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_train_ns)))

The number of classes before fit Counter({0: 199001, 1: 363})
The number of classes after fit Counter({0: 199001, 1: 99500})


In [91]:
classifier.fit(X_train_ns,y_train_ns)

RandomForestClassifier()

In [92]:
y_pred=classifier.predict(X_test)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85314
           1       0.97      0.79      0.87       129

    accuracy                           1.00     85443
   macro avg       0.99      0.90      0.94     85443
weighted avg       1.00      1.00      1.00     85443

[[85311     3]
 [   27   102]]
0.9996488887328394


In [75]:
y_test.value_counts()

0    85314
1      129
Name: Class, dtype: int64

## SMOTETomek

### SMOTE (Synthetic Minority Over-sampling Technique): SMOTE is an oversampling technique that is used to address class imbalance by generating synthetic examples of the minority class. It works by creating synthetic data points between existing minority class instances. These synthetic samples help balance the class distribution and prevent the model from being biased towards the majority class.

SMOTE is first applied to oversample the minority class and generate synthetic samples.
Then, Tomek links are used to identify pairs of instances (one from each class) that form Tomek links. These pairs are removed to improve class separation.

In [93]:
from imblearn.combine import SMOTETomek

In [94]:
os=SMOTETomek(sampling_strategy=0.5)

In [ ]:
X_train_ns,y_train_ns=os.fit_resample(X_train,y_train)
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_train_ns)))